library(boot)
library(ggplot2)

# mle = maximum likelihood estimation of parameter

# Parametric bootstrap --> We generate and don't sample
# Generate a new dataset using the fitted parameters

############ Creating some data to play with
set.seed(12345)
x = runif(200, 0, 20)
data = data.frame(Time = x, Visitors = rpois(200, x))

ggplot() + 
  geom_point(data = data, aes(Time, Visitors))

############ A basic GLM model with poisson residuals
glm_model = glm(Visitors ~ Time, data = data, family = 'poisson')

#This is a poisson distribution: parameter lambda
generator = function(observed_data, mle) {
  
  # Lambda-param for poisson is the mean/expected value
  # Thus we will use the predictions from our model as lambda
  
  n = dim(observed_data)[1]
  yhat = rpois(n, predict(mle, observed_data, type = 'response'))
  n_data = data.frame(Time = observed_data$Time, Visitors = yhat)
  
  return(n_data)
  
}

# Statistic is a function that returns the statistic we want to measure
# by running the function on all data sets generated by generator


# Confidence bands! (= How confident are we about our regression)
# 1 Generate a new model
# 2 Make predictions
conf_bands = function(data) {
  model = glm(Visitors ~ Time, family = poisson, data)
  preds = predict(model, data, type = 'response')
  return(preds)
}

# Prediction bands! (= Where does new data end up?)
pred_bands = function(data) {
  model = glm(Visitors ~ Time, family = poisson, data)
  
  n = dim(data)[1]
  yhat = rpois(n, predict(model, data, type = 'response'))
  
  return(yhat)
  
}

boot_confint = boot(data, statistic = conf_bands, R = 1000, 
                    ran.gen = generator, mle = glm_model, sim = 'parametric')

conf_band = envelope(boot_confint)

boot_pred = boot(data, statistic = pred_bands, R = 1000, 
                 ran.gen = generator, mle = glm_model, sim = 'parametric')

pred_band = envelope(boot_pred)

ggplot(data, aes(x = Time, y = Visitors)) + 
  geom_point(color = 'black') +
  geom_line(aes(y = predict(glm_model, data, type = 'response')), color = 'red') +
  geom_ribbon(aes(ymin = conf_band$point[2,], ymax = conf_band$point[1,]),
              col="blue", fill = "blue", alpha = 0.2) + 
  geom_line(aes(y = pred_band$point[1,]), col="orange", size = 0.5) +
  geom_line(aes(y = pred_band$point[2,]), col="orange", size = 0.5) 


############ Prediction bands interval for set interval:
t = seq(20, 30, 0.05)

pred_bands_1213 = function(data) {
  model = glm(Visitors ~ Time, family = poisson, data)
  
  n = length(t)
  yhat = rpois(n, predict(model, data.frame(Time = t), type = 'response'))
  
  return(yhat)
  
}

boot_pred = boot(data, statistic = pred_bands_1213, R = 1000, 
                 ran.gen = generator, mle = glm_model, sim = 'parametric')

pred_band = envelope(boot_pred)

d1 = data.frame(x = t, y1 = pred_band$point[1,], y2 = pred_band$point[2,])
# To plot
ggplot(data, aes(x = Time, y = Visitors)) + 
  geom_point(color = 'black') +
  geom_line(aes(y = predict(glm_model, data, type = 'response')), color = 'red') +
  geom_line(data = d1, aes(x, y1), col="orange", size = 0.5) +
  geom_line(data = d1, aes(x, y2), col="orange", size = 0.5) 

